#!/bin/bash
# _     _____   ____               ____                                          _     
#| |   |  ___| |  _ \ _   _ _ __  / ___|___  _ __ ___  _ __ ___   __ _ _ __   __| |___ 
#| |   | |_    | |_) | | | | '_ \| |   / _ \| '_ ` _ \| '_ ` _ \ / _` | '_ \ / _` / __|
#| |___|  _|   |  _ <| |_| | | | | |__| (_) | | | | | | | | | | | (_| | | | | (_| \__ \
#|_____|_|     |_| \_\\__,_|_| |_|\____\___/|_| |_| |_|_| |_| |_|\__,_|_| |_|\__,_|___/
##########################################################################################
##########################################################################################
# ____       _   _   _                 
#/ ___|  ___| |_| |_(_)_ __   __ _ ___ 
#\___ \ / _ \ __| __| | '_ \ / _` / __|
# ___) |  __/ |_| |_| | | | | (_| \__ \
#|____/ \___|\__|\__|_|_| |_|\__, |___/
#                            |___/     
cmd on-start &{{
	rclone mount GoogleDrive: ~/GDrive/
}}
on-start
cmd on-cd &{{
    printf "\033]0; $PWD\007" > /dev/tty
}}
on-cd
set shell bash
set filesep " "
set number 'true'
set previewer ctpv
set cleaner ctpvclear
&ctpv -s $id
&ctpvquit $id

##########################################################################################
# __  __                 ___   ____       _           _   
#|  \/  | _____   _____ ( _ ) / ___|  ___| | ___  ___| |_ 
#| |\/| |/ _ \ \ / / _ \/ _ \/\___ \ / _ \ |/ _ \/ __| __|
#| |  | | (_) \ V /  __/ (_>  <___) |  __/ |  __/ (__| |_ 
#|_|  |_|\___/ \_/ \___|\___/\/____/ \___|_|\___|\___|\__|
#
cmd select-path ${{
    printf "Select path: "
    read -e spath
    lf -remote "send $id toggle $spath"
    lf -remote "send $id copy"
}}
cmd select-all %{{
if [ "$lf_hidden" = "false" ]; then fdfind -L $(pwd) -d 1
else fdfind -HL $(pwd) -d 1
    fi |
    sed '/^$/d' | sort | uniq -u |
    xargs -d '\n' -r -I{} lf -remote "send $id toggle {}"
}}
cmd select-files ${{
    { echo "$fs"; find -L "$(pwd)" -mindepth 1 -maxdepth 1 -type f; } |
        if [ "$lf_hidden" = "false" ]; then
          # remove any hidden files so you only select files you can see.
          grep -v '/\.[^/]\+$'
        else
          cat
        fi |
        sed '/^$/d' | sort | uniq -u |
        xargs -d '\n' -r -I{} lf -remote "send $id toggle {}"
}}
cmd select-type %{{
    if [ "$lf_hidden" = "false" ]; then fdfind -L -d 1 -t d
    else fdfind -HL -d 1 -t d
    fi | sed '/^$/d' | sort | uniq -u |
    xargs -d '\n' -r -I{} lf -remote "send $id toggle {}"
}}
#cmd newtypestart select $latestdir
#cmd newtypeend select $latestdir

##########################################################################################
# __  __       _         ___   ____       _      _       
#|  \/  | __ _| | _____ ( _ ) |  _ \  ___| | ___| |_ ___ 
#| |\/| |/ _` | |/ / _ \/ _ \/\ | | |/ _ \ |/ _ \ __/ _ \
#| |  | | (_| |   <  __/ (_>  < |_| |  __/ |  __/ ||  __/
#|_|  |_|\__,_|_|\_\___|\___/\/____/ \___|_|\___|\__\___|
#
cmd mkparentdir %{{
    printf "Name New Parent Directory: "
    read latestdir
    if [ $lf_count -gt 1 ]; then
        for dir in ${latestdir}; do
            mkdir -p $(seq -f "../${dir}%g" ${lf_count})
        done
    else
        mkdir -p ../${latestdir}
    fi
    #lf -remote "send $id cd ../${latestdir}"
}}
cmd mksubdir %{{
    printf "Name New Subdirectory: "
    read latestdir
    if [ $lf_count -gt 1 ]; then
        for dir in ${latestdir}; do
            mkdir -p $(seq -f "${dir}%g" ${lf_count})
        done
    else
        mkdir -p ${latestdir}
    fi
    #lf -remote "send $id cd ${latestdir}"
}}
cmd newfile %{{
    printf "Name new file(s): "
    read newfilename
    if [ $lf_count -gt 1 ]; then
        for file in ${newfilename}; do
            touch $(seq -f "${file}%g" ${lf_count})
        done
    else
        touch ${newfilename}
    fi
}}

##########################################################################################
# _____    _ _ _   ___   ____                                 
#| ____|__| (_) |_( _ ) |  _ \ ___ _ __   __ _ _ __ ___   ___ 
#|  _| / _` | | __/ _ \/\ |_) / _ \ '_ \ / _` | '_ ` _ \ / _ \
#| |__| (_| | | || (_>  <  _ <  __/ | | | (_| | | | | | |  __/
#|_____\__,_|_|\__\___/\/_| \_\___|_| |_|\__,_|_| |_| |_|\___|
#                                                             
cmd append %{{
    printf "Append to selected file(s): "
    read appendage
    for file in $fx; do
        for i in `seq $lf_count`; do
            echo ${appendage} >> ${file}
        done
    done
}}
cmd appendnew %{{
    printf "Append to new file(s): "
    read appendage
    printf "Name file(s): "
    read newfilename
    touch ${newfilename}
    for file in ${newfilename}; do
        for i in `seq $lf_count`; do
            echo ${appendage} >> ${file}
        done
    done
}}
cmd bulk-rename ${{
    old="$(mktemp)"
    new="$(mktemp)"
    if [ -n "$fs" ]; then
        fs="$(basename -a $fs)"
    else
        fs="$(ls)"
    fi
    printf '%s\n' "$fs" >"$old"
    printf '%s\n' "$fs" >"$new"
    $EDITOR "$new"
    [ "$(wc -l < "$new")" -ne "$(wc -l < "$old")" ] && exit 
    paste "$old" "$new" | while IFS= read -r names; do
        src="$(printf '%s' "$names" | cut -f1)"
        dst="$(printf '%s' "$names" | cut -f2)"
        if [ "$src" = "$sdt" ] || [ -e "$dst" ]; then
            continue
        fi
        mv -- "$src" "$dst"
    done
    rm -- "$old" "$new"
    lf -remote "send $id unselect"
}}

##########################################################################################
# _  __          __  __                   _             
#| |/ /___ _   _|  \/  | __ _ _ __  _ __ (_)_ __   __ _ 
#| ' // _ \ | | | |\/| |/ _` | '_ \| '_ \| | '_ \ / _` |
#| . \  __/ |_| | |  | | (_| | |_) | |_) | | | | | (_| |
#|_|\_\___|\__, |_|  |_|\__,_| .__/| .__/|_|_| |_|\__, |
#          |___/             |_|   |_|            |___/ 
map [
map ]
map ^ jump-firstfile
map <c-i> jump-next
map <c-o> jump-prev
map . set hidden!
map a append
map A appendnew
map b jump-startprevioustype
map B jump-startprevioustype
map c
map d
map dd move-all %{{
    find ~+ -maxdepth 1 | sed '1s/.*/move/' > ~/.local/share/lf/files
    lf -remote "send $id sync"
}}
map dl cut
map d/ select-path
map e jump-endnexttype
map E jump-endnexttype
map gg
map gg cd /
map gt ${{tmux send-keys -t 0 "cd $PWD && ls" Enter}}
map G
map G cd
map i ${{tmux send-keys -t 1 Escape ":argd * | tabd | argadd" Enter ":argadd $fx | tab all" Enter}}
map I newfile
map O mkparentdir
map o mksubdir
map u :{{
    clear
    unselect
}}
map w jump-startnexttype
map W jump-startnexttype
map x delete 
map y
map yy copy-all %{{
    find ~+ -maxdepth 1 | sed '1s/.*/copy/' > ~/.local/share/lf/files
    lf -remote "send $id sync"
}}
map yl copy
map y/ select-path
